# Generated by Django 5.2.3 on 2025-06-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('lastname', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
            ],
        ),
    ]
