# Generated by Django 5.2.3 on 2025-06-22 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cliente',
            new_name='Client',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='nome',
        ),
    ]
